### ISSUE TITLE
Missing module?

### ISSUE THREAD

**Issue by Roberto7766** [KanishkNavale/DQN-FrozenLake#1]
Hi,
I'm using Colab. I cloned the project (git clone https://github.com/KanishkNavale/DoubleDQN.git) and launched the file (python train.py). It returns:

Traceback (most recent call last):
  File "/content/DoubleDQN/train.py", line 10, in <module>
    from DDQN import Agent
  File "/content/DoubleDQN/DDQN.py", line 9, in <module>
    from replay_buffers.Uniform import ReplayBuffer
ModuleNotFoundError: No module named 'replay_buffers'

Am I doing something wrong?
Thank you

**Comment by KanishkNavale** [comment]
Hello, 

Please add the code from here:
https://github.com/KanishkNavale/Trajectory-Planning-using-HER-and-Reward-Engineering/tree/master/replay_buffers
